/*
 * This file is generated by jOOQ.
*/
package org.jooq.no.skotbuvel.portal.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.no.skotbuvel.portal.DefaultSchema;
import org.jooq.no.skotbuvel.portal.Indexes;
import org.jooq.no.skotbuvel.portal.Keys;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class member extends TableImpl<org.jooq.no.skotbuvel.portal.tables.records.member> {

    private static final long serialVersionUID = -1701020641;

    /**
     * The reference instance of <code>member</code>
     */
    public static final member member = new member();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<org.jooq.no.skotbuvel.portal.tables.records.member> getRecordType() {
        return org.jooq.no.skotbuvel.portal.tables.records.member.class;
    }

    /**
     * The column <code>member.id</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.member, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>member.person_id</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.member, Integer> person_id = createField("person_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>member.payment_date</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.member, OffsetDateTime> payment_date = createField("payment_date", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * The column <code>member.membership_id</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.member, Integer> membership_id = createField("membership_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>member.created_by</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.member, String> created_by = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>member.created_date</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.member, OffsetDateTime> created_date = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * The column <code>member.updated_by</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.member, String> updated_by = createField("updated_by", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>member.updated_date</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.member, OffsetDateTime> updated_date = createField("updated_date", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * Create a <code>member</code> table reference
     */
    public member() {
        this(DSL.name("member"), null);
    }

    /**
     * Create an aliased <code>member</code> table reference
     */
    public member(String alias) {
        this(DSL.name(alias), member);
    }

    /**
     * Create an aliased <code>member</code> table reference
     */
    public member(Name alias) {
        this(alias, member);
    }

    private member(Name alias, Table<org.jooq.no.skotbuvel.portal.tables.records.member> aliased) {
        this(alias, aliased, null);
    }

    private member(Name alias, Table<org.jooq.no.skotbuvel.portal.tables.records.member> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.member_pkey);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<org.jooq.no.skotbuvel.portal.tables.records.member> getPrimaryKey() {
        return Keys.member_pkey;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<org.jooq.no.skotbuvel.portal.tables.records.member>> getKeys() {
        return Arrays.<UniqueKey<org.jooq.no.skotbuvel.portal.tables.records.member>>asList(Keys.member_pkey);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<org.jooq.no.skotbuvel.portal.tables.records.member, ?>> getReferences() {
        return Arrays.<ForeignKey<org.jooq.no.skotbuvel.portal.tables.records.member, ?>>asList(Keys.member__member_person_id_fkey);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public member as(String alias) {
        return new member(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public member as(Name alias) {
        return new member(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public member rename(String name) {
        return new member(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public member rename(Name name) {
        return new member(name, null);
    }
}
