/*
 * This file is generated by jOOQ.
*/
package org.jooq.no.skotbuvel.portal.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.no.skotbuvel.portal.DefaultSchema;
import org.jooq.no.skotbuvel.portal.Indexes;
import org.jooq.no.skotbuvel.portal.Keys;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class person extends TableImpl<org.jooq.no.skotbuvel.portal.tables.records.person> {

    private static final long serialVersionUID = -4344713;

    /**
     * The reference instance of <code>person</code>
     */
    public static final person person = new person();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<org.jooq.no.skotbuvel.portal.tables.records.person> getRecordType() {
        return org.jooq.no.skotbuvel.portal.tables.records.person.class;
    }

    /**
     * The column <code>person.id</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.person, Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>person.first_name</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.person, String> first_name = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>person.last_name</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.person, String> last_name = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>person.email</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.person, String> email = createField("email", org.jooq.impl.SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>person.phone</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.person, String> phone = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>person.created_by</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.person, String> created_by = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>person.created_date</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.person, OffsetDateTime> created_date = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * The column <code>person.updated_by</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.person, String> updated_by = createField("updated_by", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>person.updated_date</code>.
     */
    public final TableField<org.jooq.no.skotbuvel.portal.tables.records.person, OffsetDateTime> updated_date = createField("updated_date", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * Create a <code>person</code> table reference
     */
    public person() {
        this(DSL.name("person"), null);
    }

    /**
     * Create an aliased <code>person</code> table reference
     */
    public person(String alias) {
        this(DSL.name(alias), person);
    }

    /**
     * Create an aliased <code>person</code> table reference
     */
    public person(Name alias) {
        this(alias, person);
    }

    private person(Name alias, Table<org.jooq.no.skotbuvel.portal.tables.records.person> aliased) {
        this(alias, aliased, null);
    }

    private person(Name alias, Table<org.jooq.no.skotbuvel.portal.tables.records.person> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.person_pkey);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<org.jooq.no.skotbuvel.portal.tables.records.person> getPrimaryKey() {
        return Keys.person_pkey;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<org.jooq.no.skotbuvel.portal.tables.records.person>> getKeys() {
        return Arrays.<UniqueKey<org.jooq.no.skotbuvel.portal.tables.records.person>>asList(Keys.person_pkey);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public person as(String alias) {
        return new person(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public person as(Name alias) {
        return new person(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public person rename(String name) {
        return new person(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public person rename(Name name) {
        return new person(name, null);
    }
}
