/*
 * This file is generated by jOOQ.
*/
package org.jooq.no.skotbuvel.portal;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.no.skotbuvel.portal.tables.member;
import org.jooq.no.skotbuvel.portal.tables.membership;
import org.jooq.no.skotbuvel.portal.tables.person;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 807437021;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>member</code>.
     */
    public final member member = org.jooq.no.skotbuvel.portal.tables.member.member;

    /**
     * The table <code>membership</code>.
     */
    public final membership membership = org.jooq.no.skotbuvel.portal.tables.membership.membership;

    /**
     * The table <code>person</code>.
     */
    public final person person = org.jooq.no.skotbuvel.portal.tables.person.person;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            member.member,
            membership.membership,
            person.person);
    }
}
