/*
 * This file is generated by jOOQ.
*/
package org.jooq.no.skotbuvel.portal;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.jooq.no.skotbuvel.portal.tables.Member;
import org.jooq.no.skotbuvel.portal.tables.Membership;
import org.jooq.no.skotbuvel.portal.tables.Person;
import org.jooq.no.skotbuvel.portal.tables.records.MemberRecord;
import org.jooq.no.skotbuvel.portal.tables.records.MembershipRecord;
import org.jooq.no.skotbuvel.portal.tables.records.PersonRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MemberRecord> MEMBER_PKEY = UniqueKeys0.MEMBER_PKEY;
    public static final UniqueKey<MembershipRecord> MEMBERSHIP_PKEY = UniqueKeys0.MEMBERSHIP_PKEY;
    public static final UniqueKey<PersonRecord> PERSON_PKEY = UniqueKeys0.PERSON_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MemberRecord, PersonRecord> MEMBER__MEMBER_PERSON_ID_FKEY = ForeignKeys0.MEMBER__MEMBER_PERSON_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<MemberRecord> MEMBER_PKEY = createUniqueKey(Member.MEMBER, "member_pkey", Member.MEMBER.ID);
        public static final UniqueKey<MembershipRecord> MEMBERSHIP_PKEY = createUniqueKey(Membership.MEMBERSHIP, "membership_pkey", Membership.MEMBERSHIP.ID);
        public static final UniqueKey<PersonRecord> PERSON_PKEY = createUniqueKey(Person.PERSON, "person_pkey", Person.PERSON.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<MemberRecord, PersonRecord> MEMBER__MEMBER_PERSON_ID_FKEY = createForeignKey(org.jooq.no.skotbuvel.portal.Keys.PERSON_PKEY, Member.MEMBER, "member__member_person_id_fkey", Member.MEMBER.PERSON_ID);
    }
}
