/*
 * This file is generated by jOOQ.
*/
package org.jooq.no.skotbuvel.portal;


import javax.annotation.Generated;

import org.jooq.no.skotbuvel.portal.tables.Membership;
import org.jooq.no.skotbuvel.portal.tables.MembershipType;
import org.jooq.no.skotbuvel.portal.tables.Person;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>membership</code>.
     */
    public static final Membership MEMBERSHIP = org.jooq.no.skotbuvel.portal.tables.Membership.MEMBERSHIP;

    /**
     * The table <code>membership_type</code>.
     */
    public static final MembershipType MEMBERSHIP_TYPE = org.jooq.no.skotbuvel.portal.tables.MembershipType.MEMBERSHIP_TYPE;

    /**
     * The table <code>person</code>.
     */
    public static final Person PERSON = org.jooq.no.skotbuvel.portal.tables.Person.PERSON;
}
