/*
 * This file is generated by jOOQ.
*/
package no.skotbuvel.portal.jooq.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import no.skotbuvel.portal.jooq.tables.SubjectRole;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubjectRoleRecord extends UpdatableRecordImpl<SubjectRoleRecord> implements Record8<Integer, Integer, Integer, Boolean, String, OffsetDateTime, String, OffsetDateTime> {

    private static final long serialVersionUID = -1871668401;

    /**
     * Setter for <code>subject_role.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>subject_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>subject_role.subject_id</code>.
     */
    public void setSubjectId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>subject_role.subject_id</code>.
     */
    public Integer getSubjectId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>subject_role.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>subject_role.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>subject_role.active</code>.
     */
    public void setActive(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>subject_role.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>subject_role.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>subject_role.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>subject_role.created_date</code>.
     */
    public void setCreatedDate(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>subject_role.created_date</code>.
     */
    public OffsetDateTime getCreatedDate() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>subject_role.deleted_by</code>.
     */
    public void setDeletedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>subject_role.deleted_by</code>.
     */
    public String getDeletedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>subject_role.deleted_date</code>.
     */
    public void setDeletedDate(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>subject_role.deleted_date</code>.
     */
    public OffsetDateTime getDeletedDate() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Integer, Integer, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Boolean, String, OffsetDateTime, String, OffsetDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Boolean, String, OffsetDateTime, String, OffsetDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SubjectRole.SUBJECT_ROLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SubjectRole.SUBJECT_ROLE.SUBJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return SubjectRole.SUBJECT_ROLE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return SubjectRole.SUBJECT_ROLE.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SubjectRole.SUBJECT_ROLE.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field6() {
        return SubjectRole.SUBJECT_ROLE.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SubjectRole.SUBJECT_ROLE.DELETED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field8() {
        return SubjectRole.SUBJECT_ROLE.DELETED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSubjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component6() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDeletedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component8() {
        return getDeletedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSubjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value6() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDeletedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value8() {
        return getDeletedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubjectRoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubjectRoleRecord value2(Integer value) {
        setSubjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubjectRoleRecord value3(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubjectRoleRecord value4(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubjectRoleRecord value5(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubjectRoleRecord value6(OffsetDateTime value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubjectRoleRecord value7(String value) {
        setDeletedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubjectRoleRecord value8(OffsetDateTime value) {
        setDeletedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubjectRoleRecord values(Integer value1, Integer value2, Integer value3, Boolean value4, String value5, OffsetDateTime value6, String value7, OffsetDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubjectRoleRecord
     */
    public SubjectRoleRecord() {
        super(SubjectRole.SUBJECT_ROLE);
    }

    /**
     * Create a detached, initialised SubjectRoleRecord
     */
    public SubjectRoleRecord(Integer id, Integer subjectId, Integer roleId, Boolean active, String createdBy, OffsetDateTime createdDate, String deletedBy, OffsetDateTime deletedDate) {
        super(SubjectRole.SUBJECT_ROLE);

        set(0, id);
        set(1, subjectId);
        set(2, roleId);
        set(3, active);
        set(4, createdBy);
        set(5, createdDate);
        set(6, deletedBy);
        set(7, deletedDate);
    }
}
