/*
 * This file is generated by jOOQ.
*/
package no.skotbuvel.portal.jooq;


import javax.annotation.Generated;

import no.skotbuvel.portal.jooq.tables.Membership;
import no.skotbuvel.portal.jooq.tables.MembershipType;
import no.skotbuvel.portal.jooq.tables.Person;
import no.skotbuvel.portal.jooq.tables.Role;
import no.skotbuvel.portal.jooq.tables.Subject;
import no.skotbuvel.portal.jooq.tables.SubjectRole;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MEMBERSHIP_PKEY = Indexes0.MEMBERSHIP_PKEY;
    public static final Index MEMBERSHIP_TYPE_PKEY = Indexes0.MEMBERSHIP_TYPE_PKEY;
    public static final Index PERSON_PKEY = Indexes0.PERSON_PKEY;
    public static final Index ROLE_PKEY = Indexes0.ROLE_PKEY;
    public static final Index SUBJECT_PKEY = Indexes0.SUBJECT_PKEY;
    public static final Index SUBJECT_ROLE_PKEY = Indexes0.SUBJECT_ROLE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index MEMBERSHIP_PKEY = createIndex("membership_pkey", Membership.MEMBERSHIP, new OrderField[] { Membership.MEMBERSHIP.ID }, true);
        public static Index MEMBERSHIP_TYPE_PKEY = createIndex("membership_type_pkey", MembershipType.MEMBERSHIP_TYPE, new OrderField[] { MembershipType.MEMBERSHIP_TYPE.ID }, true);
        public static Index PERSON_PKEY = createIndex("person_pkey", Person.PERSON, new OrderField[] { Person.PERSON.ID }, true);
        public static Index ROLE_PKEY = createIndex("role_pkey", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
        public static Index SUBJECT_PKEY = createIndex("subject_pkey", Subject.SUBJECT, new OrderField[] { Subject.SUBJECT.ID }, true);
        public static Index SUBJECT_ROLE_PKEY = createIndex("subject_role_pkey", SubjectRole.SUBJECT_ROLE, new OrderField[] { SubjectRole.SUBJECT_ROLE.ID, SubjectRole.SUBJECT_ROLE.SUBJECT_ID, SubjectRole.SUBJECT_ROLE.ROLE_ID }, true);
    }
}
