/*
 * This file is generated by jOOQ.
*/
package no.skotbuvel.portal.jooq;


import javax.annotation.Generated;

import no.skotbuvel.portal.jooq.tables.Membership;
import no.skotbuvel.portal.jooq.tables.MembershipType;
import no.skotbuvel.portal.jooq.tables.Person;
import no.skotbuvel.portal.jooq.tables.Role;
import no.skotbuvel.portal.jooq.tables.User;
import no.skotbuvel.portal.jooq.tables.UserRole;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>membership</code>.
     */
    public static final Membership MEMBERSHIP = no.skotbuvel.portal.jooq.tables.Membership.MEMBERSHIP;

    /**
     * The table <code>membership_type</code>.
     */
    public static final MembershipType MEMBERSHIP_TYPE = no.skotbuvel.portal.jooq.tables.MembershipType.MEMBERSHIP_TYPE;

    /**
     * The table <code>person</code>.
     */
    public static final Person PERSON = no.skotbuvel.portal.jooq.tables.Person.PERSON;

    /**
     * The table <code>role</code>.
     */
    public static final Role ROLE = no.skotbuvel.portal.jooq.tables.Role.ROLE;

    /**
     * The table <code>user</code>.
     */
    public static final User USER = no.skotbuvel.portal.jooq.tables.User.USER;

    /**
     * The table <code>user_role</code>.
     */
    public static final UserRole USER_ROLE = no.skotbuvel.portal.jooq.tables.UserRole.USER_ROLE;
}
