/*
 * This file is generated by jOOQ.
*/
package no.skotbuvel.portal.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import no.skotbuvel.portal.jooq.DefaultSchema;
import no.skotbuvel.portal.jooq.Indexes;
import no.skotbuvel.portal.jooq.Keys;
import no.skotbuvel.portal.jooq.tables.records.SubjectRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subject extends TableImpl<SubjectRecord> {

    private static final long serialVersionUID = -758246584;

    /**
     * The reference instance of <code>subject</code>
     */
    public static final Subject SUBJECT = new Subject();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SubjectRecord> getRecordType() {
        return SubjectRecord.class;
    }

    /**
     * The column <code>subject.id</code>.
     */
    public final TableField<SubjectRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('subject_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>subject.original_id</code>.
     */
    public final TableField<SubjectRecord, Integer> ORIGINAL_ID = createField("original_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>subject.active</code>.
     */
    public final TableField<SubjectRecord, Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>subject.first_name</code>.
     */
    public final TableField<SubjectRecord, String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>subject.last_name</code>.
     */
    public final TableField<SubjectRecord, String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>subject.email</code>.
     */
    public final TableField<SubjectRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>subject.phone</code>.
     */
    public final TableField<SubjectRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>subject.created_by</code>.
     */
    public final TableField<SubjectRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>subject.created_date</code>.
     */
    public final TableField<SubjectRecord, OffsetDateTime> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    /**
     * The column <code>subject.deleted_by</code>.
     */
    public final TableField<SubjectRecord, String> DELETED_BY = createField("deleted_by", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>subject.deleted_date</code>.
     */
    public final TableField<SubjectRecord, OffsetDateTime> DELETED_DATE = createField("deleted_date", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * Create a <code>subject</code> table reference
     */
    public Subject() {
        this(DSL.name("subject"), null);
    }

    /**
     * Create an aliased <code>subject</code> table reference
     */
    public Subject(String alias) {
        this(DSL.name(alias), SUBJECT);
    }

    /**
     * Create an aliased <code>subject</code> table reference
     */
    public Subject(Name alias) {
        this(alias, SUBJECT);
    }

    private Subject(Name alias, Table<SubjectRecord> aliased) {
        this(alias, aliased, null);
    }

    private Subject(Name alias, Table<SubjectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SUBJECT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SubjectRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SUBJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SubjectRecord> getPrimaryKey() {
        return Keys.SUBJECT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SubjectRecord>> getKeys() {
        return Arrays.<UniqueKey<SubjectRecord>>asList(Keys.SUBJECT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Subject as(String alias) {
        return new Subject(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Subject as(Name alias) {
        return new Subject(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Subject rename(String name) {
        return new Subject(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Subject rename(Name name) {
        return new Subject(name, null);
    }
}
