/*
 * This file is generated by jOOQ.
*/
package org.jooq.no.skotbuvel.portal.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class member extends UpdatableRecordImpl<member> implements Record8<Integer, Integer, OffsetDateTime, Integer, String, OffsetDateTime, String, OffsetDateTime> {

    private static final long serialVersionUID = 622920190;

    /**
     * Setter for <code>member.id</code>.
     */
    public void id(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>member.id</code>.
     */
    public Integer id() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>member.person_id</code>.
     */
    public void person_id(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>member.person_id</code>.
     */
    public Integer person_id() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>member.payment_date</code>.
     */
    public void payment_date(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>member.payment_date</code>.
     */
    public OffsetDateTime payment_date() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>member.membership_id</code>.
     */
    public void membership_id(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>member.membership_id</code>.
     */
    public Integer membership_id() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>member.created_by</code>.
     */
    public void created_by(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>member.created_by</code>.
     */
    public String created_by() {
        return (String) get(4);
    }

    /**
     * Setter for <code>member.created_date</code>.
     */
    public void created_date(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>member.created_date</code>.
     */
    public OffsetDateTime created_date() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>member.updated_by</code>.
     */
    public void updated_by(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>member.updated_by</code>.
     */
    public String updated_by() {
        return (String) get(6);
    }

    /**
     * Setter for <code>member.updated_date</code>.
     */
    public void updated_date(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>member.updated_date</code>.
     */
    public OffsetDateTime updated_date() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, OffsetDateTime, Integer, String, OffsetDateTime, String, OffsetDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, OffsetDateTime, Integer, String, OffsetDateTime, String, OffsetDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return org.jooq.no.skotbuvel.portal.tables.member.member.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return org.jooq.no.skotbuvel.portal.tables.member.member.person_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field3() {
        return org.jooq.no.skotbuvel.portal.tables.member.member.payment_date;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return org.jooq.no.skotbuvel.portal.tables.member.member.membership_id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return org.jooq.no.skotbuvel.portal.tables.member.member.created_by;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field6() {
        return org.jooq.no.skotbuvel.portal.tables.member.member.created_date;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return org.jooq.no.skotbuvel.portal.tables.member.member.updated_by;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field8() {
        return org.jooq.no.skotbuvel.portal.tables.member.member.updated_date;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return person_id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component3() {
        return payment_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return membership_id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return created_by();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component6() {
        return created_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return updated_by();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component8() {
        return updated_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return person_id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value3() {
        return payment_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return membership_id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return created_by();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value6() {
        return created_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return updated_by();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value8() {
        return updated_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public member value1(Integer value) {
        id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public member value2(Integer value) {
        person_id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public member value3(OffsetDateTime value) {
        payment_date(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public member value4(Integer value) {
        membership_id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public member value5(String value) {
        created_by(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public member value6(OffsetDateTime value) {
        created_date(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public member value7(String value) {
        updated_by(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public member value8(OffsetDateTime value) {
        updated_date(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public member values(Integer value1, Integer value2, OffsetDateTime value3, Integer value4, String value5, OffsetDateTime value6, String value7, OffsetDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached member
     */
    public member() {
        super(org.jooq.no.skotbuvel.portal.tables.member.member);
    }

    /**
     * Create a detached, initialised member
     */
    public member(Integer id, Integer person_id, OffsetDateTime payment_date, Integer membership_id, String created_by, OffsetDateTime created_date, String updated_by, OffsetDateTime updated_date) {
        super(org.jooq.no.skotbuvel.portal.tables.member.member);

        set(0, id);
        set(1, person_id);
        set(2, payment_date);
        set(3, membership_id);
        set(4, created_by);
        set(5, created_date);
        set(6, updated_by);
        set(7, updated_date);
    }
}
