/*
 * This file is generated by jOOQ.
*/
package org.jooq.no.skotbuvel.portal.tables.records;


import java.sql.Date;
import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class membership extends UpdatableRecordImpl<membership> implements Record8<Integer, String, Date, Integer, String, OffsetDateTime, String, OffsetDateTime> {

    private static final long serialVersionUID = -1735374518;

    /**
     * Setter for <code>membership.id</code>.
     */
    public void id(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>membership.id</code>.
     */
    public Integer id() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>membership.type</code>.
     */
    public void type(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>membership.type</code>.
     */
    public String type() {
        return (String) get(1);
    }

    /**
     * Setter for <code>membership.year</code>.
     */
    public void year(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>membership.year</code>.
     */
    public Date year() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>membership.price</code>.
     */
    public void price(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>membership.price</code>.
     */
    public Integer price() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>membership.created_by</code>.
     */
    public void created_by(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>membership.created_by</code>.
     */
    public String created_by() {
        return (String) get(4);
    }

    /**
     * Setter for <code>membership.created_date</code>.
     */
    public void created_date(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>membership.created_date</code>.
     */
    public OffsetDateTime created_date() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>membership.updated_by</code>.
     */
    public void updated_by(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>membership.updated_by</code>.
     */
    public String updated_by() {
        return (String) get(6);
    }

    /**
     * Setter for <code>membership.updated_date</code>.
     */
    public void updated_date(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>membership.updated_date</code>.
     */
    public OffsetDateTime updated_date() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Date, Integer, String, OffsetDateTime, String, OffsetDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Date, Integer, String, OffsetDateTime, String, OffsetDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return org.jooq.no.skotbuvel.portal.tables.membership.membership.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return org.jooq.no.skotbuvel.portal.tables.membership.membership.type;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return org.jooq.no.skotbuvel.portal.tables.membership.membership.year;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return org.jooq.no.skotbuvel.portal.tables.membership.membership.price;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return org.jooq.no.skotbuvel.portal.tables.membership.membership.created_by;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field6() {
        return org.jooq.no.skotbuvel.portal.tables.membership.membership.created_date;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return org.jooq.no.skotbuvel.portal.tables.membership.membership.updated_by;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field8() {
        return org.jooq.no.skotbuvel.portal.tables.membership.membership.updated_date;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return type();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return year();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return price();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return created_by();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component6() {
        return created_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return updated_by();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component8() {
        return updated_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return type();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return year();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return price();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return created_by();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value6() {
        return created_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return updated_by();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value8() {
        return updated_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public membership value1(Integer value) {
        id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public membership value2(String value) {
        type(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public membership value3(Date value) {
        year(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public membership value4(Integer value) {
        price(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public membership value5(String value) {
        created_by(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public membership value6(OffsetDateTime value) {
        created_date(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public membership value7(String value) {
        updated_by(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public membership value8(OffsetDateTime value) {
        updated_date(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public membership values(Integer value1, String value2, Date value3, Integer value4, String value5, OffsetDateTime value6, String value7, OffsetDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached membership
     */
    public membership() {
        super(org.jooq.no.skotbuvel.portal.tables.membership.membership);
    }

    /**
     * Create a detached, initialised membership
     */
    public membership(Integer id, String type, Date year, Integer price, String created_by, OffsetDateTime created_date, String updated_by, OffsetDateTime updated_date) {
        super(org.jooq.no.skotbuvel.portal.tables.membership.membership);

        set(0, id);
        set(1, type);
        set(2, year);
        set(3, price);
        set(4, created_by);
        set(5, created_date);
        set(6, updated_by);
        set(7, updated_date);
    }
}
