/*
 * This file is generated by jOOQ.
*/
package org.jooq.no.skotbuvel.portal.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class person extends UpdatableRecordImpl<person> implements Record9<Integer, String, String, String, String, String, OffsetDateTime, String, OffsetDateTime> {

    private static final long serialVersionUID = -250142332;

    /**
     * Setter for <code>person.id</code>.
     */
    public void id(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>person.id</code>.
     */
    public Integer id() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>person.first_name</code>.
     */
    public void first_name(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>person.first_name</code>.
     */
    public String first_name() {
        return (String) get(1);
    }

    /**
     * Setter for <code>person.last_name</code>.
     */
    public void last_name(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>person.last_name</code>.
     */
    public String last_name() {
        return (String) get(2);
    }

    /**
     * Setter for <code>person.email</code>.
     */
    public void email(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>person.email</code>.
     */
    public String email() {
        return (String) get(3);
    }

    /**
     * Setter for <code>person.phone</code>.
     */
    public void phone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>person.phone</code>.
     */
    public String phone() {
        return (String) get(4);
    }

    /**
     * Setter for <code>person.created_by</code>.
     */
    public void created_by(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>person.created_by</code>.
     */
    public String created_by() {
        return (String) get(5);
    }

    /**
     * Setter for <code>person.created_date</code>.
     */
    public void created_date(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>person.created_date</code>.
     */
    public OffsetDateTime created_date() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>person.updated_by</code>.
     */
    public void updated_by(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>person.updated_by</code>.
     */
    public String updated_by() {
        return (String) get(7);
    }

    /**
     * Setter for <code>person.updated_date</code>.
     */
    public void updated_date(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>person.updated_date</code>.
     */
    public OffsetDateTime updated_date() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, String, OffsetDateTime, String, OffsetDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, String, OffsetDateTime, String, OffsetDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return org.jooq.no.skotbuvel.portal.tables.person.person.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return org.jooq.no.skotbuvel.portal.tables.person.person.first_name;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return org.jooq.no.skotbuvel.portal.tables.person.person.last_name;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return org.jooq.no.skotbuvel.portal.tables.person.person.email;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return org.jooq.no.skotbuvel.portal.tables.person.person.phone;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return org.jooq.no.skotbuvel.portal.tables.person.person.created_by;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field7() {
        return org.jooq.no.skotbuvel.portal.tables.person.person.created_date;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return org.jooq.no.skotbuvel.portal.tables.person.person.updated_by;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field9() {
        return org.jooq.no.skotbuvel.portal.tables.person.person.updated_date;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return first_name();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return last_name();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return email();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return phone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return created_by();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component7() {
        return created_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return updated_by();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component9() {
        return updated_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return first_name();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return last_name();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return email();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return phone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return created_by();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value7() {
        return created_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return updated_by();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value9() {
        return updated_date();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public person value1(Integer value) {
        id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public person value2(String value) {
        first_name(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public person value3(String value) {
        last_name(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public person value4(String value) {
        email(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public person value5(String value) {
        phone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public person value6(String value) {
        created_by(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public person value7(OffsetDateTime value) {
        created_date(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public person value8(String value) {
        updated_by(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public person value9(OffsetDateTime value) {
        updated_date(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public person values(Integer value1, String value2, String value3, String value4, String value5, String value6, OffsetDateTime value7, String value8, OffsetDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached person
     */
    public person() {
        super(org.jooq.no.skotbuvel.portal.tables.person.person);
    }

    /**
     * Create a detached, initialised person
     */
    public person(Integer id, String first_name, String last_name, String email, String phone, String created_by, OffsetDateTime created_date, String updated_by, OffsetDateTime updated_date) {
        super(org.jooq.no.skotbuvel.portal.tables.person.person);

        set(0, id);
        set(1, first_name);
        set(2, last_name);
        set(3, email);
        set(4, phone);
        set(5, created_by);
        set(6, created_date);
        set(7, updated_by);
        set(8, updated_date);
    }
}
